name: divyashr.com.np Deployement
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      deploy:
        description: Enter 'staging' to deploy to staging
        required: true
        default: 'no'

jobs:
  deployment:
    name: 🎉 Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftpupload.net
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          server-dir: 'divyashr.com.np/htdocs/'
      - name: Notify slack on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_MESSAGE: "Deployment successful"
          SLACK_ICON: ":nepadey:"
          SLACK_USERNAME: "Deployer"

      - name: Notify slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_MESSAGE: "Deployment failed"
          SLACK_ICON: ":nepadey:"
          SLACK_USERNAME: "Deployer"
